version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo_container
    profiles:
      - dev
    ports:
      - 27017:27017
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - ./docker/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always

  tenant_service:
    image: registry.thinhlh.com/tenant_service
    container_name: tenant_container
    ports:
      - 8002:3000
    environment:
      - MONGO_INITDB_HOST
      - MONGO_INITDB_PORT
      - MONGO_INITDB_DATABASE
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - AUTH_HOST
      - AUTH_PORT
    depends_on:
      - mongo

networks:
  app_network:
    driver: bridge
    external: true
